# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      # Primary container image where all steps run
      - image:
          circleci/node:10
          # auth:
          #   username: mydockerhub-user
          #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run: echo "A first hello"
      - run: npm -v
